SYMPTOM_LABELS = {
    "itching": "Picazón",
    "skin_rash": "Erupción en la piel",
    "nodal_skin_eruptions": "Nódulos o granos en la piel",
    "continuous_sneezing": "Estornudos continuos",
    "shivering": "Temblores",
    "chills": "Escalofríos",
    "joint_pain": "Dolor articular",
    "stomach_pain": "Dolor de estómago",
    "acidity": "Acidez",
    "ulcers_on_tongue": "Úlceras en la lengua",
    "muscle_wasting": "Pérdida de masa muscular",
    "vomiting": "Vómitos",
    "burning_micturition": "Ardor al orinar",
    "spotting_ urination": "Goteo o manchado al orinar",
    "fatigue": "Fatiga",
    "weight_gain": "Aumento de peso",
    "anxiety": "Ansiedad",
    "cold_hands_and_feets": "Manos y pies fríos",
    "mood_swings": "Cambios de humor",
    "weight_loss": "Pérdida de peso",
    "restlessness": "Inquietud",
    "lethargy": "Letargo",
    "patches_in_throat": "Placas en la garganta",
    "irregular_sugar_level": "Azúcar irregular en sangre",
    "cough": "Tos",
    "high_fever": "Fiebre alta",
    "sunken_eyes": "Ojos hundidos",
    "breathlessness": "Falta de aire",
    "sweating": "Sudoración",
    "dehydration": "Deshidratación",
    "indigestion": "Indigestión",
    "headache": "Dolor de cabeza",
    "yellowish_skin": "Piel amarillenta",
    "dark_urine": "Orina oscura",
    "nausea": "Náuseas",
    "loss_of_appetite": "Pérdida de apetito",
    "pain_behind_the_eyes": "Dolor detrás de los ojos",
    "back_pain": "Dolor de espalda",
    "constipation": "Estreñimiento",
    "abdominal_pain": "Dolor abdominal",
    "diarrhoea": "Diarrea",
    "mild_fever": "Fiebre leve",
    "yellow_urine": "Orina muy amarilla",
    "yellowing_of_eyes": "Ojos amarillos",
    "acute_liver_failure": "Falla hepática aguda",
    "fluid_overload": "Retención de líquidos",
    "swelling_of_stomach": "Hinchazón del estómago",
    "swelled_lymph_nodes": "Ganglios inflamados",
    "malaise": "Malestar general",
    "blurred_and_distorted_vision": "Visión borrosa o distorsionada",
    "phlegm": "Flema",
    "throat_irritation": "Irritación de garganta",
    "redness_of_eyes": "Ojos enrojecidos",
    "sinus_pressure": "Presión en los senos paranasales",
    "runny_nose": "Congestión o goteo nasal",
    "congestion": "Congestión",
    "chest_pain": "Dolor de pecho",
    "weakness_in_limbs": "Debilidad en brazos o piernas",
    "fast_heart_rate": "Latidos acelerados",
    "pain_during_bowel_movements": "Dolor al evacuar",
    "pain_in_anal_region": "Dolor en la zona anal",
    "bloody_stool": "Sangre en las heces",
    "irritation_in_anus": "Irritación anal",
    "neck_pain": "Dolor de cuello",
    "dizziness": "Mareos",
    "cramps": "Calambres",
    "bruising": "Moretones fáciles",
    "obesity": "Obesidad",
    "swollen_legs": "Piernas hinchadas",
    "swollen_blood_vessels": "Vasos sanguíneos inflamados",
    "puffy_face_and_eyes": "Rostro u ojos hinchados",
    "enlarged_thyroid": "Tiroides agrandada",
    "brittle_nails": "Uñas quebradizas",
    "swollen_extremeties": "Extremidades hinchadas",
    "excessive_hunger": "Hambre excesiva",
    "extra_marital_contacts": "Contactos sexuales de riesgo",
    "drying_and_tingling_lips": "Labios secos u hormigueo",
    "slurred_speech": "Habla arrastrada",
    "knee_pain": "Dolor de rodilla",
    "hip_joint_pain": "Dolor de cadera",
    "muscle_weakness": "Debilidad muscular",
    "stiff_neck": "Cuello rígido",
    "swelling_joints": "Articulaciones hinchadas",
    "movement_stiffness": "Rigidez al moverse",
    "spinning_movements": "Sensación de que todo gira",
    "loss_of_balance": "Pérdida del equilibrio",
    "unsteadiness": "Inestabilidad al caminar",
    "weakness_of_one_body_side": "Debilidad de un lado del cuerpo",
    "loss_of_smell": "Pérdida del olfato",
    "bladder_discomfort": "Molestia en la vejiga",
    "foul_smell_of_urine": "Orina con mal olor",
    "continuous_feel_of_urine": "Ganas constantes de orinar",
    "passage_of_gases": "Gases intestinales",
    "internal_itching": "Picazón interna",
    "toxic_look_(typhos)": "Aspecto muy comprometido o tóxica",
    "depression": "Ánimo muy bajo",
    "irritability": "Irritabilidad",
    "muscle_pain": "Dolor muscular",
    "altered_sensorium": "Confusión o alteración de la conciencia",
    "red_spots_over_body": "Manchas rojas en el cuerpo",
    "belly_pain": "Dolor de vientre",
    "abnormal_menstruation": "Menstruación anormal",
    "dischromic _patches": "Manchas en la piel",
    "watering_from_eyes": "Lagrimeo",
    "increased_appetite": "Aumento del apetito",
    "polyuria": "Orina en exceso",
    "family_history": "Antecedente familiar",
    "mucoid_sputum": "Esputo con moco",
    "rusty_sputum": "Esputo color óxido",
    "lack_of_concentration": "Falta de concentración",
    "visual_disturbances": "Alteraciones de la visión",
    "receiving_blood_transfusion": "Transfusión de sangre reciente",
    "receiving_unsterile_injections": "Inyección con material no estéril",
    "coma": "Pérdida de conciencia",
    "stomach_bleeding": "Sangrado estomacal",
    "distention_of_abdomen": "Abdomen distendido",
    "history_of_alcohol_consumption": "Consumo importante de alcohol",
    "blood_in_sputum": "Sangre al toser",
    "prominent_veins_on_calf": "Venas marcadas en la pantorrilla",
    "palpitations": "Palpitaciones",
    "painful_walking": "Dolor al caminar",
    "pus_filled_pimples": "Granos con pus",
    "blackheads": "Puntos negros",
    "scurring": "Cicatrización o costras",
    "skin_peeling": "Descamación de la piel",
    "silver_like_dusting": "Escamas plateadas en la piel",
    "small_dents_in_nails": "Hoyuelos en las uñas",
    "inflammatory_nails": "Uñas inflamadas",
    "blister": "Ampollas",
    "red_sore_around_nose": "Llaga roja alrededor de la nariz",
    "yellow_crust_ooze": "Costra amarilla que supura",
}

DISEASE_LABELS = {
    "Hepatitis A": "Hepatitis A",
    "Hepatitis B": "Hepatitis B",
    "Hepatitis C": "Hepatitis C",
    "Hepatitis D": "Hepatitis D",
    "Hepatitis E": "Hepatitis E",
    "Alcoholic hepatitis": "Hepatitis alcohólica",
    "Tuberculosis": "Tuberculosis",
    "Common Cold": "Resfriado común",
    "Pneumonia": "Neumonía",
    "Dimorphic hemmorhoids(piles)": "Hemorroides",
    "Heart attack": "Infarto de miocardio",
    "Varicose veins": "Várices",
    "Acne": "Acné",
    "AIDS": "VIH / sida",
    "Dengue fever": "Dengue",
    "Diabetes": "Diabetes",
    "Gastroenteritis": "Gastroenteritis",
    "Bronchial Asthma": "Asma bronquial",
    "Hypertension": "Hipertensión",
    "Migraine": "Migraña",
    "Cervical spondylosis": "Espondilosis cervical",
    "Paralysis (brain hemorrhage)": "Parálisis por hemorragia cerebral",
    "Jaundice": "Ictericia",
    "Malaria": "Malaria",
    "Chicken pox": "Varicela",
    "Dengue": "Dengue",
    "Typhoid": "Fiebre tifoidea",
    "Fungal infection": "Infección por hongos",
    "Allergy": "Alergia",
    "GERD": "Reflujo gastroesofágico",
    "Chronic cholestasis": "Colestasis crónica",
    "Drug Reaction": "Reacción a un medicamento",
    "Hypothyroidism": "Hipotiroidismo",
    "Hyperthyroidism": "Hipertiroidismo",
    "Hypoglycemia": "Hipoglucemia",
    "Arthritis": "Artritis",
    "(vertigo) Paroymsal  Positional Vertigo": "Vértigo posicional",
    "Urinary tract infection": "Infección urinaria",
    "Psoriasis": "Psoriasis",
    "Impetigo": "Impétigo",
    "Osteoarthristis": "Osteoartritis",
    "Peptic ulcer diseae": "Úlcera péptica",
}

CATEGORIES = {
    "piel": {
        "label": "Piel o alergia",
        "question": "En la piel, ¿reconoce alguno de estos cambios? Puede marcar varios o ninguno.",
        "symptoms": [
            "itching", "skin_rash", "nodal_skin_eruptions", "red_spots_over_body",
            "pus_filled_pimples", "blackheads", "blister", "skin_peeling",
            "silver_like_dusting", "yellow_crust_ooze", "red_sore_around_nose",
            "dischromic _patches",
        ],
    },
    "fiebre": {
        "label": "Fiebre o infección",
        "question": "Cuando hay fiebre o un cuadro infeccioso, suelo preguntar esto. ¿Le suena alguno?",
        "symptoms": [
            "high_fever", "mild_fever", "chills", "shivering", "sweating",
            "malaise", "fatigue", "headache", "muscle_pain", "swelled_lymph_nodes",
        ],
    },
    "respiratorio": {
        "label": "Respiración, tos o nariz",
        "question": "Hablemos de la vía respiratoria. ¿Qué está notando?",
        "symptoms": [
            "cough", "breathlessness", "continuous_sneezing", "runny_nose",
            "congestion", "phlegm", "throat_irritation", "sinus_pressure",
            "loss_of_smell", "blood_in_sputum", "rusty_sputum", "chest_pain",
        ],
    },
    "digestivo": {
        "label": "Estómago o digestión",
        "question": "En el aparato digestivo, ¿cuál de estas molestias está presente?",
        "symptoms": [
            "stomach_pain", "abdominal_pain", "belly_pain", "nausea", "vomiting",
            "diarrhoea", "constipation", "acidity", "indigestion", "loss_of_appetite",
            "ulcers_on_tongue", "bloody_stool",
        ],
    },
    "urinario": {
        "label": "Orina o vejiga",
        "question": "Con molestias urinarias pregunto esto. ¿Identifica alguno?",
        "symptoms": [
            "burning_micturition", "spotting_ urination", "bladder_discomfort",
            "foul_smell_of_urine", "continuous_feel_of_urine", "polyuria",
            "dark_urine", "yellow_urine",
        ],
    },
    "dolor": {
        "label": "Dolor (cabeza, pecho, huesos)",
        "question": "El dolor hay que ubicarlo. ¿Dónde lo siente con más claridad?",
        "symptoms": [
            "headache", "chest_pain", "joint_pain", "back_pain", "neck_pain",
            "knee_pain", "hip_joint_pain", "muscle_pain", "pain_behind_the_eyes",
            "painful_walking",
        ],
    },
    "circulo": {
        "label": "Corazón o circulación",
        "question": "Voy a preguntarle por el corazón y la circulación. ¿Nota algo de esto?",
        "symptoms": [
            "chest_pain", "palpitations", "fast_heart_rate", "sweating",
            "breathlessness", "swollen_legs", "prominent_veins_on_calf",
            "dizziness",
        ],
    },
    "neurologico": {
        "label": "Mareos, visión o conciencia",
        "question": "Estos signos me importan mucho. ¿Ha tenido alguno?",
        "symptoms": [
            "dizziness", "spinning_movements", "loss_of_balance", "unsteadiness",
            "slurred_speech", "altered_sensorium", "weakness_of_one_body_side",
            "blurred_and_distorted_vision", "visual_disturbances", "coma",
        ],
    },
}

CONTEXT_MAP = {
    "medicamento": {
        "label": "Tomó un medicamento nuevo",
        "symptom": None,
        "note": "Mencionó un medicamento reciente. Una reacción adversa es posible; no suspenda tratamientos crónicos por su cuenta.",
    },
    "droga": {
        "label": "Ingirió alguna droga o sustancia",
        "symptom": None,
        "note": "Hubo consumo de una sustancia. Eso cambia el enfoque: si hay fiebre, erupción, dolor de pecho o confusión, debe evaluarse en un hospital.",
    },
    "alcohol": {
        "label": "Consumo importante de alcohol",
        "symptom": "history_of_alcohol_consumption",
        "note": "El consumo reciente de alcohol puede explicar o agravar un cuadro hepático o digestivo.",
    },
    "relaciones": {
        "label": "Contacto sexual de riesgo",
        "symptom": "extra_marital_contacts",
        "note": "Un contacto de riesgo obliga a considerar infecciones de transmisión sexual en la evaluación presencial.",
    },
    "transfusion": {
        "label": "Transfusión de sangre",
        "symptom": "receiving_blood_transfusion",
        "note": "Una transfusión reciente es un antecedente que el médico debe conocer.",
    },
    "inyeccion": {
        "label": "Inyección con material no estéril",
        "symptom": "receiving_unsterile_injections",
        "note": "Una inyección no estéril aumenta el riesgo de infecciones; conviene una evaluación presencial.",
    },
    "familia": {
        "label": "Antecedente familiar similar",
        "symptom": "family_history",
        "note": "Los antecedentes familiares ayudan, pero no reemplazan un examen clínico.",
    },
}

EMERGENCY_SYMPTOMS = {
    "chest_pain",
    "breathlessness",
    "coma",
    "stomach_bleeding",
    "blood_in_sputum",
    "weakness_of_one_body_side",
    "slurred_speech",
    "altered_sensorium",
    "acute_liver_failure",
    "bloody_stool",
    "toxic_look_(typhos)",
}

EMERGENCY_COMBOS = [
    {"chest_pain", "sweating"},
    {"chest_pain", "breathlessness"},
    {"high_fever", "altered_sensorium"},
    {"high_fever", "dehydration"},
    {"vomiting", "dehydration", "sunken_eyes"},
]

NON_CLINICAL = {
    "extra_marital_contacts",
    "family_history",
    "receiving_blood_transfusion",
    "receiving_unsterile_injections",
    "history_of_alcohol_consumption",
}


def label_symptom(symptom_id: str) -> str:
    return SYMPTOM_LABELS.get(symptom_id, symptom_id.replace("_", " "))


def label_disease(disease_id: str) -> str:
    return DISEASE_LABELS.get(disease_id, disease_id)


def category_of(symptom_id: str) -> tuple[str, str]:
    for key, data in CATEGORIES.items():
        if symptom_id in data["symptoms"]:
            return key, data["label"]
    return "otros", "Otros"
